from . import mate_hms_mixin
from . import mate_hms_base
from . import mate_hms_consumable_line
from . import mate_partner
from . import mate_patient
from . import mate_physician
from . import mate_product
from . import mate_drug
from . import mate_country
from . import stock_move
from . import account
from . import res_config
from . import ir_sequence
